FROM elixir:1.18-alpine

ENV MIX_ENV=dev
ENV ERL_AFLAGS="-kernel shell_history enabled"
ENV LANG=C.UTF-8

RUN apk add --no-cache \
    git \
    build-base \
    inotify-tools \
    bash 
    
RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /app

COPY mix.exs mix.lock ./

RUN mix deps.get

COPY . .

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 4000

ENTRYPOINT ["entrypoint.sh"]